language: php
php:
  - "5.4"
before_script:
  - composer install
script:
  - phpunit

notifications:
  webhooks:
    - url: https://idobata.io/hook/circle_ci/0dc171ee-8076-4075-8794-8ec91f995743
  emails:
    - eiji.ienaga@gmail.com
  on_success: always # default: change
  on_failure: always
